### ISSUE TITLE
Todo/Planned features

### ISSUE THREAD

**Issue by CaptainProton42** [CaptainProton42/GodotHoloPlay#5]
- [ ] Standalone mode that hides the main window and only displays the hologram
- [ ] Hologram recorder for creating quilts/videos
- [ ] Add a toggle/property to temporarily disable hologram rendering without removing the node from the tree
